// Auto-generated by LibreLane
module rca(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input rst,
  input[15:0] a,
  input[15:0] b,
  input cin,
  input[2:0] delay_sel,
  output[15:0] s,
  output cout,
  output tdo
);
endmodule
