// Auto-generated by LibreLane
module pmu(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input se,
  input[7:0] path,
  input[2:0] path_sel,
  input[2:0] delay_sel,
  input tdi,
  output tdo
);
endmodule
